exports.poemsAll = [
  [
    "della mia carne",
    "nell'ombra per Mantova",
    "l'ascolta, la sera i platani",
    "sul capo prossimo il gelo",
    "dondolano alte nel mucchio",
    "sotto i cieli a gran carrozza",
    "23*0*20*0*6.7*5.3*7.75",
  ],
  [
    "mezzogiorno?",
    "col rombo suol che fugge",
    "nel mio stracciglio",
    "teco il bollente soltanto",
    "6*6*12*45*28.04*22.8*8.03",
  ],
  [
    "dietro il Mantova cielo",
    "non mai piú",
    "delle bollente ombra",
    "all'alba! disse la fede pianta",
    "6*6*6*45*27.27*28.1*7.6",
  ],
  [
    "tiepidi pazzi del biondo",
    "nel vecchio velo nero",
    "tósseco di te non ci abbriare",
    "dall’altre vate",
    "sei piú sfumanti la sera il mondo",
    "ed ora che il sol stritolar",
    "4*6*18*30*28.05*35.5*8.39",
  ],
  [
    "sui capelli d'alberi",
    "dode sulle pietre",
    "ghiaccia ora il vento",
    "dire, nel sogno, il primo sole",
    "di civetti schiarazzo",
    "la dolce vostra alla notte trovo",
  ],
  [
    "il sole sopra di tormenta",
    "quando nel bosco ne canto",
    "iechi ai cieli dell’Alpe",
    "ma il crepuscolo le stelle",
    "come al vino che ti sa né il male",
    "bollente, nelle pugnaci chiome",
    "ad ogni ch'è silenzio",
    "5*6*20*15*28.1*34.4*8.2",
  ],
  [
    "e prostrata",
    "al crepuscolo! A lei sommerso",
    "la lunga, fredda anch'ella",
    "Mantova si spiega smanie",
    "di fuor dell'amore",
    "4*6*20*30*28.08*35.5*8.39",
  ],
  [
    "la vita nova",
    "troppo fresco bianco",
    "svolgesi dall'alba ",
    "delle campane, che seppi",
    "4*6*6*30*26.89*27.8*7.73",
  ],
  [
    "sul Mar alla notte d’Egia",
    "pensata una rovente ",
    "dietro le spighe se ne fa l'umido",
    "sospira per Mantova",
    "6*6*23*30*27.93*33.8*7.99",
  ],
  [
    "alba che viene, che viene di cera!",
    "che non sai",
    "come tante volte ai templi",
    "con un filo di vita",
    "come sia il tiepido triste",
    "come una viva vivontana",
    "5*6*8*45*26.88*23.3*7.71",
  ],
  [
    "il mattino - la zolla",
    "son ben un fresco io dell'arte",
    "al fiume de l'acque istratto",
    "o tante le nostre confuse",
    "4*6*8*15*26.74*23.2*7.61",
  ],
  [
    "son bollente d'amore",
    "correre un poco a chi cammino",
    "della sua salsia",
    "sopra il lago",
    "sgorgò, al crepuscolo bianco",
    "5*6*18*30*28.22*32*8.2",
  ],
  [
    "poich'ella il caldo",
    "notte delle stelle nel cielo",
    "or che l’incanto",
    "aurea cinta di cori",
    "4*6*23*45*27.85*34*8.38",
  ],
  [
    "dolce un mattino pesato d'amarezza",
    "o non so che canteri",
    "e un gelido tu, quando avventa",
    "salve, serena voce!",
    "è il tuo cervello",
    "non di che la vidi",
    "23*0*8*30*6.35*6.6*7.61",
  ],
  [
    "l tuo colore che non ci affonda",
    "com'essere di Mantova pareva",
    "tu suoni e vendi",
    "non le prime luci ma la cammina",
    "e quest’aromi gelidi",
    "24*0*11*15*6.41*4.1*7.54",
  ],
  [
    "dentro rompe il tuo viso d'argento",
    "or mi ridi",
    "quest'esile' bollente",
    "d'un poeta un mattino errorori",
    "e nel limpido augello",
    "salve, d'amore",
    "4*6*1*0*27.28*36.8*7.82",
  ],
  [
    "la sfiorita",
    "m'insegnò quel bimbetto",
    "ed il mondo era pur gelido",
    "che andavoli e là",
    "di sera",
    "sul suo tetto",
    "24*0*17*45*6.74*4.3*7.77",
  ],
  [
    "Albeggiano la fredda fanci",
    "mezzodì tra i baci",
    "mantova attraverso i segni",
    "sguardo sullo stessesti rese",
    "24*0*12*45*6.54*3.9*6.97",
  ],
  [
    "dinnanzi mezzogiorno",
    "freddo se l'avessi",
    "ora mi ricordo, o giovinezza!",
    "ora, laurensi, spira",
    "dagli specchi",
    "25*0*13*15*6.58*8.1*7.78",
  ],
  [
    "d'oro e di tedio",
    "cenere e cenere",
    "come mezzogiorno nel cugino",
    "te d’un lume lago ",
    "non vide al mio",
    "23*0*17*30*6.78*5.6*7.76",
  ],
  [
    "gelido aquilone",
    "le tempie bianche",
    "ad una volta nera",
    "sì che in sì di mezzodì faragherone",
    "piantato nella scena scuotoni",
    "23*0*16*30*6.82*4.5*7.75",
  ],
  [
    "che sera mi amai, che serpi",
    "sotto il liscio del fiume",
    "febbraio 1883",
    "d'antichi il gelido",
    "dove nel Lago di Mezzo",
    "23*0*21*0*6.7*4.8*7.7",
  ],
  [
    "o bella bene al mondo",
    "in questa solitudine",
    "sul mattino tuo cavallo",
    "ed i profumi pascoli",
    "e ti sentí con te mio",
    "25*0*6*15*6.58*5.4*7.78",
  ],
  [
    "",
    "l'agile di mezzogiorno",
    "nei giorni di Mantova vegli",
    "la voce della gazza",
    "io ti sentii nel freddo cielo",
    "opera con un suo pispume",
    "sfiorita",
    "24*0*17*30*6.74*3.5*7.77",
  ],
  [
    "che l'erba è la notte nervatura",
    "della stanchezza",
    "statuidi i veli",
    "freddo ondeggia",
    "chi Mantova che ti chiedevo",
    "23*0*4*0*6.62*5.8*7.67",
  ],
  [
    "proclea sogni!",
    "la sposa nell'ultima disciplina",
    "s'abbuotando il silenzio di pianto",
    "gelido, stanco d'amore",
    "crepuscolo, la rasa",
    "24*0*21*30*6.56*6*7.76",
  ],
  [
    "ghigna passata di treni",
    "freschezza la notte",
    "pia verde carte scuotezzate",
    "freddo parea paura",
    "era pur sotto un brusio vento",
    "con Mantova corolle",
    "25*0*3*0*6.55*6.4*7.78",
  ],
  [
    "il tuo sorriso",
    "di me, freddo non crocidio",
    "Una volta ancora, e non l'avvenire",
    "di notte e notte e piovai",
    "del cielo e della terra",
    "24*0*1*0*6.64*6.1*7.73",
  ],
  [
    "lenta in mezzo i laghi ai boschi",
    "il caldo nostro stagno",
    "il mattino occhi parmi",
    "e posanta la figliuola",
    "ritorno candido",
    "e a lui ride aspre",
    "24*0*6*45*6.55*6*7.73",
  ],
  [
    "la tua torcia di chi spogliare",
    "per ciò che amammo",
    "sul giorno nascente solitaria",
    "e il gelido nel cielo",
    "23*0*5*0*6.57*4.9*7.7",
  ],
]
